### ISSUE TITLE
Lizenz

### ISSUE THREAD

**Issue by duhzzz** [cydolo/AGodZilla#10]
Ich hätte gerne eine Lizenz :D

640T0kJrCDMIdoJQSl7M2Eudgmw=

**Comment by duhzzz** [comment]
Wie kann ich die Lizenz aktivieren?

**Comment by cydolo** [comment]
Herz > Activate > Upload Identity (.ini FIle)

**Comment by duhzzz** [comment]
thx

**Comment by Bluscream** [comment]
pls

**Comment by MaximilianGT500** [comment]
Kann ich eine Lizenz haben? :)
