### ISSUE TITLE
AGodZilla License Error

### ISSUE THREAD

**Issue by HighLikeRampage** [cydolo/AGodZilla#20]
Dateiname: "C:\Users\Censored\...\qweqwqwe_files\ASettings\ALicense.ini" not found
Hallo, Dolo ich habe ein Problem meine Lizenz wurde Aktiviert ich Aktivierte meine Lizenz bzw. versuchte es und dann kam der Fehler "ALicense.ini" not found und die .exe Crashte wenn es möglich wäre
HighLikeRampage#2094 (Bin in Dein Discord) oder Schreib hier auf Github..

**Comment by cydolo** [comment]
Sende mir bitte die vollständige Fehlermeldung.

**Comment by HighLikeRampage** [comment]
Wäre besser wenn du auf Discord schreibst..
Aktuelle .net Framework habe ich auch
Windows Updates alles habe ich..
Fehlermeldung:

Informationen über das Aufrufen von JIT-Debuggen
anstelle dieses Dialogfelds finden Sie am Ende dieser Meldung.

************** Ausnahmetext **************
System.IO.FileNotFoundException: Die Datei "C:\Users\censored\...\qweqwqwe_files\ASettings\ALicense.ini" konnte nicht gefunden werden.
Dateiname: "C:\Users\censored\...\qweqwqwe_files\ASettings\ALicense.ini"
   bei System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   bei System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   bei System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize)
   bei  .(String )
   bei  .(Object , EventArgs )
   bei System.Windows.Forms.ToolStripItem.RaiseEvent(Object key, EventArgs e)
   bei System.Windows.Forms.ToolStripMenuItem.OnClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleClick(EventArgs e)
   bei System.Windows.Forms.ToolStripItem.HandleMouseUp(MouseEventArgs e)
   bei System.Windows.Forms.ToolStrip.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.ToolStripDropDown.OnMouseUp(MouseEventArgs mea)
   bei System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   bei System.Windows.Forms.Control.WndProc(Message& m)
   bei System.Windows.Forms.ToolStrip.WndProc(Message& m)
   bei System.Windows.Forms.ToolStripDropDown.WndProc(Message& m)
   bei System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Geladene Assemblys **************
mscorlib
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll.
----------------------------------------
AGodZilla
    Assembly-Version: 3.0.1.0.
    Win32-Version: 3.0.1.0.
    CodeBase: file:///C:/Users/Daymarr/Videos/qweqwqwe_files/AGodZilla.exe.
----------------------------------------
System.Windows.Forms
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll.
----------------------------------------
System
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll.
----------------------------------------
System.Drawing
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll.
----------------------------------------
System.Configuration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll.
----------------------------------------
System.Core
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll.
----------------------------------------
System.Xml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll.
----------------------------------------
PresentationCore
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/PresentationCore/v4.0_4.0.0.0__31bf3856ad364e35/PresentationCore.dll.
----------------------------------------
WindowsBase
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsBase/v4.0_4.0.0.0__31bf3856ad364e35/WindowsBase.dll.
----------------------------------------
Qt5Gui
    Assembly-Version: 5.6.2.0.
    Win32-Version: 5.6.2.0.
    CodeBase: file:///C:/Users/Daymarr/Videos/qweqwqwe_files/Qt5Gui.DLL.
----------------------------------------
netstandard
    Assembly-Version: 2.0.0.0.
    Win32-Version: 4.8.3646.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll.
----------------------------------------
TSFive
    Assembly-Version: 1.0.0.0.
    Win32-Version: 1.0.0.0.
    CodeBase: file:///C:/Users/Daymarr/Videos/qweqwqwe_files/TSFive.DLL.
----------------------------------------
System.Memory
    Assembly-Version: 4.0.1.0.
    Win32-Version: 4.6.26606.05.
    CodeBase: file:///C:/Users/Daymarr/Videos/qweqwqwe_files/System.Memory.DLL.
----------------------------------------
TradeWright.TabControlExtra
    Assembly-Version: 2.0.0.0.
    Win32-Version: 2.0.0.0.
    CodeBase: file:///C:/Users/Daymarr/Videos/qweqwqwe_files/TradeWright.TabControlExtra.DLL.
----------------------------------------
Accessibility
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll.
----------------------------------------
NLog
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.5.9.8171.
    CodeBase: file:///C:/Users/Daymarr/Videos/qweqwqwe_files/NLog.DLL.
----------------------------------------
WindowsFormsIntegration
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/WindowsFormsIntegration/v4.0_4.0.0.0__31bf3856ad364e35/WindowsFormsIntegration.dll.
----------------------------------------
PresentationFramework
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.dll.
----------------------------------------
System.Xaml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xaml/v4.0_4.0.0.0__b77a5c561934e089/System.Xaml.dll.
----------------------------------------
mscorlib.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_de_b77a5c561934e089/mscorlib.resources.dll.
----------------------------------------
PresentationFramework.Aero2
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework.Aero2/v4.0_4.0.0.0__31bf3856ad364e35/PresentationFramework.Aero2.dll.
----------------------------------------
PresentationFramework-SystemXml
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationFramework-SystemXml/v4.0_4.0.0.0__b77a5c561934e089/PresentationFramework-SystemXml.dll.
----------------------------------------
PresentationCore.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/PresentationCore.resources/v4.0_4.0.0.0_de_31bf3856ad364e35/PresentationCore.resources.dll.
----------------------------------------
Flurl.Http
    Assembly-Version: 2.4.0.0.
    Win32-Version: 2.4.0.0.
    CodeBase: file:///C:/Users/censored/.../qweqwqwe_files/Flurl.Http.DLL.
----------------------------------------
System.Net.Http
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0 built by: NET48REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Net.Http/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll.
----------------------------------------
Flurl
    Assembly-Version: 2.8.0.0.
    Win32-Version: 2.8.0.0.
    CodeBase: file:///C:/Users/censored/.../qweqwqwe_files/Flurl.DLL.
----------------------------------------
Newtonsoft.Json
    Assembly-Version: 11.0.0.0.
    Win32-Version: 11.0.2.21924.
    CodeBase: file:///C:/Users/censored/..../qweqwqwe_files/Newtonsoft.Json.DLL.
----------------------------------------
System.ValueTuple
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.ValueTuple/v4.0_4.0.0.0__cc7b13ffcd2ddd51/System.ValueTuple.dll.
----------------------------------------
BouncyCastle.Crypto
    Assembly-Version: 1.8.2.0.
    Win32-Version: 1.8.2.223.
    CodeBase: file:///C:/Users/censored/..../qweqwqwe_files/BouncyCastle.Crypto.DLL.
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly-Version: 4.0.4.0.
    Win32-Version: .
    CodeBase: file:///C:/Users/censored/.../qweqwqwe_files/System.Runtime.CompilerServices.Unsafe.DLL.
----------------------------------------
System.Runtime
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.8.3646.0.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Runtime.dll.
----------------------------------------
System.Numerics.Vectors
    Assembly-Version: 4.1.3.0.
    Win32-Version: 4.6.25519.03.
    CodeBase: file:///C:/Users/censored/,,,/qweqwqwe_files/System.Numerics.Vectors.DLL.
----------------------------------------
System.Windows.Forms.resources
    Assembly-Version: 4.0.0.0.
    Win32-Version: 4.7.3056.0 built by: NET472REL1.
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_de_b77a5c561934e089/System.Windows.Forms.resources.dll.
----------------------------------------

************** JIT-Debuggen **************
Um das JIT-Debuggen (Just-In-Time) zu aktivieren, muss in der
Konfigurationsdatei der Anwendung oder des Computers
(machine.config) der jitDebugging-Wert im Abschnitt system.windows.forms festgelegt werden.
Die Anwendung muss mit aktiviertem Debuggen kompiliert werden.

Zum Beispiel:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

Wenn das JIT-Debuggen aktiviert ist, werden alle nicht behandelten
Ausnahmen an den JIT-Debugger gesendet, der auf dem
Computer registriert ist, und nicht in diesem Dialogfeld behandelt.

**Comment by cydolo** [comment]
Erstelle mal eine Datei und nenne die `ALicense.ini ` in ASettings

**Comment by HighLikeRampage** [comment]
Dann kommt das gleiche fenster und dann steht da noch immer "Weiter oder
Beenden"
+ Invalid License

Am Sa., 23. Feb. 2019 um 20:00 Uhr schrieb Dolo <notifications@github.com>:

**Comment by cydolo** [comment]
Ich kann den Fehler nicht nachproduzieren. 
Lösch mal alles und lade es erneut runter.

**Comment by HighLikeRampage** [comment]
Okay können wir über dc schreiben? damit wir das besser diskutieren können
xd bzw ich dir dann auch screens etc schicken kann


Am Sa., 23. Feb. 2019 um 20:51 Uhr schrieb Dolo <notifications@github.com>:
