### ISSUE TITLE
AGodZilla Don`t Startup

### ISSUE THREAD

**Issue by CookieCr2nk** [cydolo/AGodZilla#6]
Heallo cydolo

I have Sucessful unzipped the packet from Github. But when i will start the Client it comes this error: https://i.imgur.com/tF6JBha.png

**Comment by CookieCr2nk** [comment]
Need i the Eazfuscator.net for use this Client?

**Comment by cydolo** [comment]
AGodZilla is obfuscated.
You dont need Eazfuscator anymore, just use the latest version.
